import "./globals.css";
import LoginModal from "./components/modals/LoginModel";
import RegisterModal from "./components/modals/RegisterModel";
import CreateModal from "./components/modals/CreateModal";
import ToasterProvider from "./providers/ToasterProvider";
import { Providers } from "./providers/providers";
import { QueryClientProviders } from "./providers/ClientProvider";
import { Footer, Header } from "./components";
import UpdateProduct from "./components/modals/UpdateProduct";
import StripeProviders from "./providers/StripeProviders";

export const metadata = {
  title: "Ecommerce App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning lang="en">
      <body suppressHydrationWarning={true}>
        <Providers>
          <StripeProviders>
            <QueryClientProviders>
              <Header />
              <ToasterProvider />
              <LoginModal />
              <RegisterModal />
              <CreateModal />
              <UpdateProduct />
              {children}
              <Footer />
            </QueryClientProviders>
          </StripeProviders>
        </Providers>
      </body>
    </html>
  );
}
